### ISSUE TITLE
sqlalchemy是不是没有事务啊？

### ISSUE THREAD

**Issue by CallMeZack** [linux-wang/sqlalchemy-docs-CN#2]
你好，想请问一下，sqlalchemy是不是没有事务transaction啊？那么它是如何保证事务处理的呢？是不是session本身当做transaction来用的呢？
默认session好像是scoped_session，与SignallingSession两者有什么区别吗？
谢谢了。

**Comment by linux-wang** [comment]
事务（类似功能）是通过session来实现的，具体的看一下http://docs.sqlalchemy.org/en/latest/orm/session_transaction.html
中文的可以参照一下http://www.codexiu.cn/python/SQLAlchemy%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B/531/
